version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql_db:3306/assessment?allowPublicKeyRetrieval=true&useSSL=false
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      SPRING_JPA_DATABASE_PLATFORM: org.hibernate.dialect.MySQL8Dialect
    depends_on:
      - mysql_db
    ports:
      - "8081:8081"
  mysql_db:
    image: mysql:8
    environment:
      MYSQL_DATABASE: assessment
      MYSQL_ROOT_PASSWORD: root
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - ./data:/var/lib/mysql
  angular_app:
    image: my-angular-app
    ports:
      - "4200:4200"
    depends_on:
      - app
volumes:
  db_data:
